import { Toolkit } from "./types";

export const transformsToolkit: Toolkit = {
  id: "transforms",
  name: "Transforms Module",
  description: "FFT, Laplace, z-domain, wavelet, and convolution building blocks",
  icon: "Activity",
  expressions: [
    {
      latex: "signal = [0, 1, 0, -1, 0, 1, 0, -1]",
      normalized: "signal=[0,1,0,-1,0,1,0,-1]",
      description: "Example bipolar pulse train",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "kernel = [0.25, 0.5, 0.25]",
      normalized: "kernel=[0.25,0.5,0.25]",
      description: "Example smoothing kernel for convolution",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "S(\\omega) = \\text{fft}(signal)",
      normalized: "S(omega)=fft(signal)",
      description: "Magnitude spectrum via registered FFT helper",
      category: "function",
      dependencies: ["signal"],
    },
    {
      latex: "S_{c}(\\omega) = \\text{fft\\_complex}(signal)",
      normalized: "S_c(omega)=fft_complex(signal)",
      description: "Complex FFT result (list of complex bins)",
      category: "function",
      dependencies: ["signal"],
    },
    {
      latex: "S_{m}(\\omega) = \\text{magnitude}(S_{c})",
      normalized: "S_m(omega)=magnitude(S_c)",
      description: "Magnitude spectrum derived from complex bins",
      category: "function",
      dependencies: ["S_c"],
    },
    {
      latex: "S_{\\phi}(\\omega) = \\text{phase}(S_{c})",
      normalized: "S_phi(omega)=phase(S_c)",
      description: "Phase spectrum of the complex FFT",
      category: "function",
      dependencies: ["S_c"],
    },
    {
      latex: "y[n] = \\text{convolve}(signal, kernel)",
      normalized: "y_n=convolve(signal,kernel)",
      description: "Discrete convolution using the built-in helper",
      category: "function",
      dependencies: ["signal", "kernel"],
    },
    {
      latex: "L\\{u(t)\\} = \\frac{1}{s}",
      normalized: "laplace_step(s)=1/s",
      description: "Laplace transform of a unit step",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "L\\{t\\} = \\frac{1}{s^{2}}",
      normalized: "laplace_ramp(s)=1/(s^2)",
      description: "Laplace transform of a ramp input",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "L\\{e^{-t}\\} = \\frac{1}{s+1}",
      normalized: "laplace_decay(s)=1/(s+1)",
      description: "Laplace transform of an exponential decay",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "Z\\{u[n]\\} = \\frac{1}{1 - z^{-1}}",
      normalized: "z_step(z)=1/(1-(z^(-1)))",
      description: "Z-transform of the unit step (causal)",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "Z\\{a^{n} u[n]\\} = \\frac{1}{1 - a z^{-1}}",
      normalized: "z_geo(z,a)=1/(1-a*(z^(-1)))",
      description: "Z-transform of a geometric progression",
      category: "definition",
      dependencies: [],
    },
    {
      latex: "\\psi_{\\text{morlet}}(t) = \\cos(5t) e^{-t^{2} / 2}",
      normalized: "psi_morlet(t)=cos(5*t)*exp(-t^2/2)",
      description: "Morlet wavelet (time-domain kernel)",
      category: "function",
      dependencies: [],
    },
    {
      latex: "w(t, s) = \\psi_{\\text{morlet}}(\\frac{t}{s})",
      normalized: "wavelet(t,s)=psi_morlet(t/s)",
      description: "Scaled wavelet useful for continuous transforms",
      category: "function",
      dependencies: ["psi_morlet"],
    },
  ],
};

